[sources.otlp_in]
type = "opentelemetry"
grpc.address = "0.0.0.0:4317"
http.address = "0.0.0.0:9090"

[transforms.to_victoriametrics_format]
type = "remap"
inputs = ["otlp_in.metrics"]
  source = '''
. = {
  "metric": merge!({"__name__": .name}, .tags),
  "values": [.value],
  "timestamps": [to_unix_timestamp!(.timestamp, unit: "milliseconds")]
}
'''

[sinks.s3_out]
type = "aws_s3"
inputs = ["to_victoriametrics_format"]
bucket = "${S3_BUCKET_NAME}"
region = "us-east-1"
key_prefix = "unbounded_metrics/"
encoding.codec = "json"
framing.method = "newline_delimited"

[sinks.vmagent_out]
type = "prometheus_remote_write"
inputs = ["otlp_in.metrics"]
endpoint = "${VMAGENT_ENDPOINT}"